## Objectives

By the end of the lesson, students should be able to:

* Train a simple scikit-learn model
* Save a trained model using joblib
* Load a saved model into a separate Python file
* Build a simple Streamlit app that collects user inputs
* Use the saved model to generate predictions in the app
* Explain why feature order and preprocessing consistency matter

In [1]:
# imports
import pandas as pd
import joblib
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

---

### Load Housing Data

We're only going to use 3 features in this model

* `Gr_Liv_Area`
* `Bedrooms`
* `Bathrooms`

In [7]:
# load in dataset, call it housing
housing = pd.read_csv("../data/ames.csv")

housing.head()

,rownames,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,Utilities,...,Fence,Misc_Feature,Misc_Val,Mo_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price,Longitude,Latitude
0,1,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,141,31770,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,...,No_Fence,NaN,0,5,2010,WD,Normal,215000,-93.619754,42.054035
1,2,One_Story_1946_and_Newer_All_Styles,Residential_High_Density,80,11622,Pave,No_Alley_Access,Regular,Lvl,AllPub,...,Minimum_Privacy,NaN,0,6,2010,WD,Normal,105000,-93.619756,42.053014
2,3,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,81,14267,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,...,No_Fence,Gar2,12500,6,2010,WD,Normal,172000,-93.619387,42.052659
3,4,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,93,11160,Pave,No_Alley_Access,Regular,Lvl,AllPub,...,No_Fence,NaN,0,4,2010,WD,Normal,244000,-93.617320,42.051245
4,5,Two_Story_1946_and_Newer,Residential_Low_Density,74,13830,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,...,Minimum_Privacy,NaN,0,3,2010,WD,Normal,189900,-93.638933,42.060899

In [8]:
housing.columns

Index(['rownames', 'MS_SubClass', 'MS_Zoning', 'Lot_Frontage', 'Lot_Area',
       'Street', 'Alley', 'Lot_Shape', 'Land_Contour', 'Utilities',
       'Lot_Config', 'Land_Slope', 'Neighborhood', 'Condition_1',
       'Condition_2', 'Bldg_Type', 'House_Style', 'Overall_Cond', 'Year_Built',
       'Year_Remod_Add', 'Roof_Style', 'Roof_Matl', 'Exterior_1st',
       'Exterior_2nd', 'Mas_Vnr_Type', 'Mas_Vnr_Area', 'Exter_Cond',
       'Foundation', 'Bsmt_Cond', 'Bsmt_Exposure', 'BsmtFin_Type_1',
       'BsmtFin_SF_1', 'BsmtFin_Type_2', 'BsmtFin_SF_2', 'Bsmt_Unf_SF',
       'Total_Bsmt_SF', 'Heating', 'Heating_QC', 'Central_Air', 'Electrical',
       'First_Flr_SF', 'Second_Flr_SF', 'Gr_Liv_Area', 'Bsmt_Full_Bath',
       'Bsmt_Half_Bath', 'Full_Bath', 'Half_Bath', 'Bedroom_AbvGr',
       'Kitchen_AbvGr', 'TotRms_AbvGrd', 'Functional', 'Fireplaces',
       'Garage_Type', 'Garage_Finish', 'Garage_Cars', 'Garage_Area',
       'Garage_Cond', 'Paved_Drive', 'Wood_Deck_SF', 'Open_Porch_SF',
       'Enclosed_Porch', 'Three_season_porch', 'Screen_Porch', 'Pool_Area',
       'Pool_QC', 'Fence', 'Misc_Feature', 'Misc_Val', 'Mo_Sold', 'Year_Sold',
       'Sale_Type', 'Sale_Condition', 'Sale_Price', 'Longitude', 'Latitude'],
      dtype='object')

In [9]:
# only grabbing columns of interest
housing = housing[['Sale_Price', 'Gr_Liv_Area', 'Bedroom_AbvGr', 'Full_Bath']].copy()

# clean up the column names
housing = housing.rename(columns={
    'Sale_Price': 'sale_price',
    'Gr_Liv_Area': 'sqft',
    'Bedroom_AbvGr': 'bedrooms',
    'Full_Bath': 'bathrooms'
})

# call .head() to check our work
housing.head()

   sale_price  sqft  bedrooms  bathrooms
0      215000  1656         3          1
1      105000   896         2          1
2      172000  1329         3          1
3      244000  2110         3          2
4      189900  1629         3          2

In [10]:
housing.drop(columns='sale_price')

      sqft  bedrooms  bathrooms
0     1656         3          1
1      896         2          1
2     1329         3          1
3     2110         3          2
4     1629         3          2
...    ...       ...        ...
2925  1003         3          1
2926   902         2          1
2927   970         3          1
2928  1389         2          1
2929  2000         3          2

[2930 rows x 3 columns]

In [11]:
# Create our feature matrix, X, and target vector, y
X = housing.drop(columns='sale_price') 
y = housing['sale_price']

# Train-test-split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [12]:
X_train.shape[0] == y_train.shape[0]

True

In [13]:
# Let's make a model and get some predictions
model = LinearRegression()

# fit it
model.fit(X_train, y_train)

LinearRegression()

In [14]:
# Get R2 Score on both training and test set
print(f"Training R2: {model.score(X_train, y_train)}")
print(f"Testing R2: {model.score(X_test, y_test)}")

Training R2: 0.5758044752252147
Testing R2: 0.6076421660805997

---

## Saving our model

Our scores are close enough on our training and test set. Let's save our model!

[Joblib](https://joblib.readthedocs.io/en/stable/)

Joblib is a set of tools to provide lightweight pipelining in Python. In particular:

transparent disk-caching of functions and lazy re-evaluation (memoize pattern)

easy simple parallel computing

Joblib is optimized to be fast and robust on large data in particular and has specific optimizations for numpy arrays.

In [15]:
# let's save our model
# use the .dump(model, 'filepath') method
joblib.dump(model, "./../models/model.joblib")

['./../models/model.joblib']